<?php namespace Tempest\Http;

use Tempest\App;

/**
 * A response generated by the HTTP kernel.
 *
 * @author Marty Wallace
 */
class Response extends Message {

	/**
	 * @return static
	 */
	public static function make() {
		return new static();
	}

	/**
	 * Send the response and {@link App::terminate() terminate} the application.
	 */
	public function send() {
		App::get()->terminate();
	}

}