<?php namespace Tempest\Http;

use Tempest\App;

/**
 * A response generated by the HTTP kernel.
 *
 * @author Marty Wallace
 */
class Response extends Message {

	/** @var string */
	private $_body = '';

	/** @var int */
	private $_status = Status::OK;

	/**
	 * @return static
	 */
	public static function make() {
		return new static();
	}

	/**
	 * Sets the response body.
	 *
	 * @param string $value The response body.
	 *
	 * @return $this
	 */
	public function body($value) {
		$this->_body = $value;
		return $this;
	}

	/**
	 * Sets the response status.
	 *
	 * @param int $value The response status.
	 *
	 * @return $this
	 */
	public function status($value) {
		$this->_status = $value;
		return $this;
	}

	/**
	 * Send the response and {@link App::terminate() terminate} the application.
	 */
	public function send() {
		http_response_code($this->_status);

		echo $this->_body;

		App::get()->terminate();
	}

}