<?php namespace Tempest\Twig;

use Tempest\HTTP\Response;


/**
 * A HTML response generated by Twig.
 *
 * @author Marty Wallace.
 */
class TwigResponse extends Response
{

	public function __construct($content = null)
	{
		parent::__construct('text/html', $content);
	}

}